[package]
name = "scoresaber-crawler"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.6.1"
lazy_static = "1"
log = "0.4.6"
regex = "1"
reqwest = "0.9.18"
rusqlite = "0.18.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"